AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  FuselessTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.foundeo.fuseless.StreamLambdaHandler
      CodeUri: ./build/distributions/fuseless-template.zip
      Runtime: java8
      Timeout: 10
      MemorySize: 3008
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          FELIX_CACHE_BUFSIZE: 16384
Outputs:
  CFMLSelectApi:
    Description: "API Gateway endpoint URL for Prod stage for CFML Select function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
